# What is PyTorch
## Tensors
tensors are similar to ndarrays but can be used on a GPU.


In [2]:
import torch

In [4]:
# uninitualized matrix
torch.empty(5, 3)

tensor([[5.3134e-08, 3.1369e+27, 7.0800e+31],
        [3.1095e-18, 1.8590e+34, 7.7767e+31],
        [7.1536e+22, 3.3803e-18, 1.9421e+31],
        [2.7491e+20, 6.1949e-04, 3.1739e+32],
        [2.3076e-12, 1.8179e+31, 1.8524e+28]])

In [5]:
# randomly initualized matrix
torch.rand(5, 3)

tensor([[0.9695, 0.1442, 0.3053],
        [0.1729, 0.8919, 0.1702],
        [0.6150, 0.0603, 0.9545],
        [0.8660, 0.8472, 0.2969],
        [0.5519, 0.8568, 0.9937]])

In [7]:
# matrix of zeros and dtype long
torch.zeros(5, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [8]:
# matrix from data. (same as np.array([]) in numpy)
torch.tensor([5, 3], dtype=torch.long)

tensor([5, 3])

In [9]:
# create matrix from a existing tensor
x = torch.rand(1, 2)
print(x)
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[0.4564, 0.9504]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.0234, -0.8037,  0.0700],
        [ 0.1455, -1.1909, -0.0990],
        [ 0.0879,  1.2669, -0.9617],
        [-0.1588, -0.7728,  1.2657],
        [-1.2453, -0.2065, -0.3687]])


In [10]:
x.size()

torch.Size([5, 3])

## Operations

In [13]:
# addition using operations
y = torch.rand(x.size())
print(y)
x + y

tensor([[0.0818, 0.9422, 0.3031],
        [0.3338, 0.0090, 0.4161],
        [0.1603, 0.7380, 0.4378],
        [0.2294, 0.7636, 0.6053],
        [0.4399, 0.2474, 0.3550]])


tensor([[ 0.0584,  0.1385,  0.3731],
        [ 0.4793, -1.1820,  0.3171],
        [ 0.2482,  2.0049, -0.5239],
        [ 0.0707, -0.0092,  1.8710],
        [-0.8054,  0.0409, -0.0138]])

In [14]:
# addition using function
torch.add(x, y)

tensor([[ 0.0584,  0.1385,  0.3731],
        [ 0.4793, -1.1820,  0.3171],
        [ 0.2482,  2.0049, -0.5239],
        [ 0.0707, -0.0092,  1.8710],
        [-0.8054,  0.0409, -0.0138]])

In [15]:
# output to tensor
out = torch.empty(x.size())
torch.add(x, y, out=out)
out

tensor([[ 0.0584,  0.1385,  0.3731],
        [ 0.4793, -1.1820,  0.3171],
        [ 0.2482,  2.0049, -0.5239],
        [ 0.0707, -0.0092,  1.8710],
        [-0.8054,  0.0409, -0.0138]])

In [16]:
# inplace operation
y.add_(x)

tensor([[ 0.0584,  0.1385,  0.3731],
        [ 0.4793, -1.1820,  0.3171],
        [ 0.2482,  2.0049, -0.5239],
        [ 0.0707, -0.0092,  1.8710],
        [-0.8054,  0.0409, -0.0138]])

In [17]:
# indexing like numpy
x[:, 1]

tensor([-0.8037, -1.1909,  1.2669, -0.7728, -0.2065])

In [20]:
# resizing/reshaping tensors
x = torch.rand(4, 4)
print(x)
print(x.view(16))
print(x.view(-1, 8))

tensor([[0.9401, 0.3889, 0.0717, 0.5138],
        [0.7982, 0.2646, 0.1858, 0.4498],
        [0.8406, 0.1096, 0.4935, 0.4325],
        [0.6287, 0.5340, 0.7644, 0.7431]])
tensor([0.9401, 0.3889, 0.0717, 0.5138, 0.7982, 0.2646, 0.1858, 0.4498, 0.8406,
        0.1096, 0.4935, 0.4325, 0.6287, 0.5340, 0.7644, 0.7431])
tensor([[0.9401, 0.3889, 0.0717, 0.5138, 0.7982, 0.2646, 0.1858, 0.4498],
        [0.8406, 0.1096, 0.4935, 0.4325, 0.6287, 0.5340, 0.7644, 0.7431]])


In [22]:
# get value of one element tensor
x = torch.randn(1)
x.item()

-1.1989820003509521

## NumPy Bridge

In [26]:
# convert to numpy array
a = torch.ones(5)
print(type(a))
b = a.numpy()
print(type(b))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [27]:
# they share the same physical memory if on cpu
print(a)
print(b)

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [28]:
# converting numpy array to tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensor

In [30]:
!nvidia-smi

Sun Oct  6 22:18:08 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 166...  Off  | 00000000:01:00.0  On |                  N/A |
| 36%   39C    P8     8W / 120W |   1400MiB /  5943MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [29]:
# move tensor by .to
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))

tensor([-0.1990], device='cuda:0')
tensor([-0.1990], dtype=torch.float64)


# Done